project:
  type: website
website:
  title: "Advanded Data Analytics and Data Science"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/kairos7139/primary
      - icon: linkedin
        href: https://www.linkedin.com/in/jonathan-jelliff/
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

